language: python

services:
  - postgresql

env:
  global:
    - ON_TRAVIS=true
    - DATABASE_URL='postgres://postgres:@localhost:5432/test_db'
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.test_travis

sudo: false
dist: xenial

python:
  - '3.7.2'

addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-9.4-postgis-2.4

install:
  - pip install codecov
  - pip install -r REQUIREMENTS-dev.txt


before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db
  - sudo apt-get -y install python-gdal
  - sudo apt-get -y install python-geoip

script:
  - cd deployment
  - make flake8
  - cd ../django_project
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput --verbosity 0
  - coverage run manage.py test

after_success:
  - codecov

email:
 - tim@kartoza.com
 - anita@kartoza.com
 - dimas@kartoza.com
