version: '2'
volumes:
  nginx-conf-data: {}
  postgis-history-data: {}
  postgis-data: {}
  django-statics-data: {}
  django-media-data: {}
services:
  smtp:
    image: catatnight/postfix
    environment:
      maildomain: kartoza.com
      smtp_user: noreply:docker
  rsync:
    image: eeacms/rsync
    stdin_open: true
    volumes:
      - django-media-data:/home/web/media:rw
    tty: true
    ports:
      - 22222:2222/tcp
    command:
      - sh
    labels:
      io.rancher.container.pull_image: always
  web:
    image: nginx
    entrypoint:
      - /etc/nginx/sites-available/docker-entrypoint.sh
    volumes:
      - nginx-conf-data:/etc/nginx/sites-available
      - django-statics-data:/home/web/static:ro
      - django-media-data:/home/web/media:ro
    links:
      - uwsgi:uwsgi
    command:
      - prod
  nginx-conf:
    image: kartoza/ford3_nginx_conf:v1.0.3-20190728
    environment:
      TARGET: /etc/nginx/sites-available
    volumes:
      - nginx-conf-data:/etc/nginx/sites-available
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  SFTP:
    image: atmoz/sftp
    stdin_open: true
    working_dir: /
    volumes:
      - postgis-history-data:/home/kartoza/ftp/postgis-history/
      - /host/id_rsa.pub:/home/kartoza/.ssh/keys/id_rsa.pub:ro
      - /host/id_other.pub:/home/kartoza/.ssh/keys/id_other.pub:ro
    tty: true
    ports:
      - 2222:22/tcp
    command:
      - kartoza::1001
    labels:
      io.rancher.container.pull_image: always
  uwsgi:
    image: dimasciput/projecta-uwsgi:latest
    environment:
      ADMIN_EMAIL: dimas@kartoza.com
      DATABASE_HOST: db
      DATABASE_NAME: gis
      DATABASE_PASSWORD: docker
      DATABASE_USERNAME: docker
      DEBUG: 'False'
      DEFAULT_FROM_EMAIL: noreply@kartoza.com
      DJANGO_ALLOWED_HOSTS: ''
      DJANGO_LOG_LEVEL: INFO
      DJANGO_SETTINGS_MODULE: core.settings.prod_docker
      EMAIL_HOST: smtp
      EMAIL_PORT: '25'
      EMAIL_SUBJECT_PREFIX: noreply@kartoza.com
      MAILDOMAIN: kartoza.com
      PYTHONPATH: /home/web/django_project
      SITEURL: www.kartoza.com
      SMTP_PASSWORD: docker
      SMTP_USER: noreply
      STRIPE_LIVE_PUBLIC_KEY: pk_live_xxx
      STRIPE_LIVE_SECRET_KEY: sk_live_xxx
    working_dir: /home/web/django_project
    volumes:
      - django-statics-data:/home/web/static:rw
      - django-media-data:/home/web/media:rw
      - django-reports:/home/web/reports
      - django-logs:/var/log/
    links:
      - smtp:smtp
      - db:db
    labels:
      io.rancher.container.start_once: 'true'
  db:
    image: kartoza/postgis:9.6-2.4
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      PGDBNAME: gis
      PGHOST: localhost
      PGPASSWORD: docker
      PGUSER: docker
      POSTGRES_DBNAME: gis
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      USERNAME: docker
      PASS: docker
    volumes:
      - postgis-data:/var/lib/postgresql
      - postgis-history-data:/backups
  dbbackups:
    image: kartoza/pg-backup:9.6
    environment:
      DUMPPREFIX: PG_CHANGELOG
      PGDATABASE: gis
      PGHOST: db
      PGPASSWORD: docker
      PGPORT: '5432'
      PGUSER: docker
    volumes:
      - postgis-history-data:/backups
    links:
      - db:db
    command:
      - /start.sh
